"""Initial schema: users, protected_users, guardians, messages, shared_messages, guardian_invitations

Revision ID: 0df9b9fa7e3c
Revises: 
Create Date: 2025-12-24 01:21:33.837454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0df9b9fa7e3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone_number'), 'users', ['phone_number'], unique=True)
    op.create_table('protected_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_protected_users_id'), 'protected_users', ['id'], unique=False)
    op.create_table('guardian_invitations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protected_user_id', sa.Integer(), nullable=False),
    sa.Column('guardian_email', sa.String(length=255), nullable=False),
    sa.Column('invitation_code', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['protected_user_id'], ['protected_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_guardian_invitations_code', 'guardian_invitations', ['invitation_code'], unique=False)
    op.create_index(op.f('ix_guardian_invitations_id'), 'guardian_invitations', ['id'], unique=False)
    op.create_index(op.f('ix_guardian_invitations_invitation_code'), 'guardian_invitations', ['invitation_code'], unique=True)
    op.create_index(op.f('ix_guardian_invitations_protected_user_id'), 'guardian_invitations', ['protected_user_id'], unique=False)
    op.create_table('guardians',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protected_user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('access_level', sa.Enum('VIEW_ALL', 'VIEW_SHARED_ONLY', name='accesslevel'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('invitation_code', sa.String(length=64), nullable=True),
    sa.Column('invitation_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('invitation_accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['protected_user_id'], ['protected_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_guardians_id'), 'guardians', ['id'], unique=False)
    op.create_index(op.f('ix_guardians_invitation_code'), 'guardians', ['invitation_code'], unique=True)
    op.create_index(op.f('ix_guardians_protected_user_id'), 'guardians', ['protected_user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protected_user_id', sa.Integer(), nullable=False),
    sa.Column('sender_phone', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('risk_level', sa.Enum('SAFE', 'MEDIUM_RISK', 'HIGH_RISK', name='risklevel'), nullable=False),
    sa.Column('rule_matches', sa.Integer(), nullable=False),
    sa.Column('ml_score', sa.String(length=10), nullable=True),
    sa.Column('analyzed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('job_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['protected_user_id'], ['protected_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_messages_analyzed_at', 'messages', ['analyzed_at'], unique=False)
    op.create_index('idx_messages_expires_at', 'messages', ['expires_at'], unique=False)
    op.create_index('idx_messages_protected_user_id', 'messages', ['protected_user_id'], unique=False)
    op.create_index(op.f('ix_messages_analyzed_at'), 'messages', ['analyzed_at'], unique=False)
    op.create_index(op.f('ix_messages_expires_at'), 'messages', ['expires_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_protected_user_id'), 'messages', ['protected_user_id'], unique=False)
    op.create_table('shared_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('guardian_id', sa.Integer(), nullable=False),
    sa.Column('encrypted_content', sa.Text(), nullable=False),
    sa.Column('shared_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['guardian_id'], ['guardians.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_shared_messages_expires_at', 'shared_messages', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shared_messages_expires_at'), 'shared_messages', ['expires_at'], unique=False)
    op.create_index(op.f('ix_shared_messages_guardian_id'), 'shared_messages', ['guardian_id'], unique=False)
    op.create_index(op.f('ix_shared_messages_id'), 'shared_messages', ['id'], unique=False)
    op.create_index(op.f('ix_shared_messages_message_id'), 'shared_messages', ['message_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shared_messages_message_id'), table_name='shared_messages')
    op.drop_index(op.f('ix_shared_messages_id'), table_name='shared_messages')
    op.drop_index(op.f('ix_shared_messages_guardian_id'), table_name='shared_messages')
    op.drop_index(op.f('ix_shared_messages_expires_at'), table_name='shared_messages')
    op.drop_index('idx_shared_messages_expires_at', table_name='shared_messages')
    op.drop_table('shared_messages')
    op.drop_index(op.f('ix_messages_protected_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_expires_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_analyzed_at'), table_name='messages')
    op.drop_index('idx_messages_protected_user_id', table_name='messages')
    op.drop_index('idx_messages_expires_at', table_name='messages')
    op.drop_index('idx_messages_analyzed_at', table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_guardians_protected_user_id'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_invitation_code'), table_name='guardians')
    op.drop_index(op.f('ix_guardians_id'), table_name='guardians')
    op.drop_table('guardians')
    op.drop_index(op.f('ix_guardian_invitations_protected_user_id'), table_name='guardian_invitations')
    op.drop_index(op.f('ix_guardian_invitations_invitation_code'), table_name='guardian_invitations')
    op.drop_index(op.f('ix_guardian_invitations_id'), table_name='guardian_invitations')
    op.drop_index('idx_guardian_invitations_code', table_name='guardian_invitations')
    op.drop_table('guardian_invitations')
    op.drop_index(op.f('ix_protected_users_id'), table_name='protected_users')
    op.drop_table('protected_users')
    op.drop_index(op.f('ix_users_phone_number'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###

